apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: etcd
    etcd_cluster: compose-etcd
  name: compose-etcd
  namespace: "${namespace}"
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd
    etcd_cluster: compose-etcd
  sessionAffinity: None
  type: ClusterIP
