#!/usr/bin/env bash
set -e

badFiles=()
for f in $(find ./api -iname '*.go'); do
	IFS=$'\n'
	badImports=( $(go list -e -f '{{ join .Deps "\n" }}' "$f" | sort -u | grep -vE '^github.com/docker/compose-on-kubernetes/api/' | grep -vE '^github.com/docker/compose-on-kubernetes/vendor' | grep -E '^github.com/docker/compose-on-kubernetes' || true) )
	unset IFS

	for import in "${badImports[@]}"; do
		badFiles+=( "$f imports $import" )
	done
done

if [ ${#badFiles[@]} -eq 0 ]; then
	echo 'Congratulations!  "./api/..." is safely isolated from internal code.'
else
	{
		echo 'These files import internal code: (either directly or indirectly)'
		for f in "${badFiles[@]}"; do
			echo " - $f"
		done
		echo
	} >&2
	false
fi