apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.deploy-namespace: docker
    com.docker.fry: compose.api
    com.docker.image-tag: latest
  name: compose-api
  namespace: "${namespace}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      com.docker.deploy-namespace: "${namespace}"
      com.docker.fry: compose.api
      com.docker.image-tag: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.docker.deploy-namespace: "${namespace}"
        com.docker.fry: compose.api
        com.docker.image-tag: latest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - args:
        - --kubeconfig
        - ""
        - --authentication-kubeconfig=
        - --authorization-kubeconfig=
        - --service-name=compose-api
        - --service-namespace
        - "${namespace}"
        - --healthz-check-port
        - "8080"
        - --etcd-servers=http://compose-etcd-client:2379
        - --secure-port=9443
        image: docker/kube-compose-api-server:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: compose
        ports:
        - containerPort: 9443
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: compose
      serviceAccountName: compose
      terminationGracePeriodSeconds: 30
